"""Asset manifest check (ARCHITECTURE.md 7.6): every asset file is listed in docs/ASSETS.md
with its source and a license from the allowlist.

Manifest format, a Markdown table (extra columns are fine):
| File | Source | License |
|---|---|---|
| assets/sfx/jump.wav | generated by the game code | original |
| assets/ui/font.ttf | https://fonts.google.com/specimen/Nunito | OFL-1.1 |
"""

from __future__ import annotations

from pathlib import Path

from harness.verify.report import CheckResult

MANIFEST = Path("docs") / "ASSETS.md"
ASSET_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp", ".svg", ".wav", ".ogg", ".mp3", ".glb", ".gltf",
                  ".obj", ".ttf", ".otf", ".woff", ".woff2"}
# original = made in this project (by the agent or procedurally); CC-BY needs attribution in the release.
LICENSES = {"original", "CC0", "CC0-1.0", "CC-BY-3.0", "CC-BY-4.0", "OFL-1.1", "MIT"}
SKIP_DIRS = {".godot", ".git", "build", "tests"}
TEMPLATE_FILES = {"icon.svg"}  # the template's own icon


def asset_files(repo: Path) -> list[str]:
    found = []
    for path in repo.rglob("*"):
        rel = path.relative_to(repo)
        if not path.is_file() or rel.parts[0] in SKIP_DIRS or path.suffix.lower() not in ASSET_SUFFIXES:
            continue
        if rel.as_posix() in TEMPLATE_FILES:
            continue
        found.append(rel.as_posix())
    return sorted(found)


def read_manifest(repo: Path) -> dict[str, dict[str, str]]:
    """File path -> row (lowercase column names). Rows of any table whose header has File and License."""
    path = repo / MANIFEST
    if not path.is_file():
        return {}
    rows: dict[str, dict[str, str]] = {}
    header: list[str] | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line.startswith("|"):
            header = None
            continue
        cells = [c.strip().strip("`") for c in line.strip("|").split("|")]
        if header is None:
            header = [c.lower() for c in cells]
            continue
        if all(set(c) <= set("-: ") for c in cells):
            continue
        if "file" in header and "license" in header:
            row = dict(zip(header, cells))
            rows[row["file"].removeprefix("res://")] = row
    return rows


def check_assets(repo: Path) -> CheckResult:
    files = asset_files(repo)
    if not files:
        return CheckResult("assets", "pass", "no asset files (graphics and sound made in code)")
    manifest = read_manifest(repo)
    problems = []
    for rel in files:
        row = manifest.get(rel)
        if row is None:
            problems.append({"message": f"{rel} is not listed in {MANIFEST.as_posix()}", "at": rel})
        elif row.get("license") not in LICENSES:
            problems.append({"message": f"{rel}: license '{row.get('license')}' is not allowed "
                                        f"(use {', '.join(sorted(LICENSES))})", "at": MANIFEST.as_posix()})
        elif not row.get("source"):
            problems.append({"message": f"{rel}: the source is empty", "at": MANIFEST.as_posix()})
    if problems:
        return CheckResult("assets", "fail", problems[0]["message"], problems)
    return CheckResult("assets", "pass", f"{len(files)} asset files, all listed with allowed licenses")
